### ISSUE TITLE
Merge repo with Fixed view of ArrayBuffer proposal

### ISSUE THREAD

**Issue by Jack-Works** [tc39-transfer/proposal-limited-arraybuffer#10]
based on the meeting conclusion. we should investigate the problem & solution together instead of one-by-one

**Comment by Jack-Works** [comment]
And I need to rephrase to focus on the problem to resolve and the design goals must be ensured (before the possible solution)

**Comment by codehag** [comment]
Should we refer to the old repo for now?

**Comment by Jack-Works** [comment]
I'm sorry I'm quite busy these days. I will merge the repo when I'm free
